apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostfound-deployment
  labels:
    app: lostfound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostfound
  template:
    metadata:
      labels:
        app: lostfound
    spec:
      containers:
        - name: lostfound-fe
          image: ayroid/lostfoundfe:latest
          ports:
            - containerPort: 4000
        - name: lostfound-be
          image: ayroid/lostfoundbe:latest
          ports:
            - containerPort: 3000
