apiVersion: v1
kind: Service
metadata:
  name: lostfound-service
spec:
  selector:
    app: lostfound
  type: LoadBalancer
  ports:
    - name: frontend-port
      protocol: TCP
      port: 5000
      targetPort: 4000
      nodePort: 30080
    - name: backend-port
      protocol: TCP
      port: 5001
      targetPort: 3000
      nodePort: 30081
